/*
 * GetListarTiposMidiaConstants
 *
 */

export const GET_LISTAR_TIPOS_MIDIA = 'app/GET_LISTAR_TIPOS_MIDIA';
export const GET_LISTAR_TIPOS_MIDIA_SUCCESS = 'app/GET_LISTAR_TIPOS_MIDIA_SUCCESS';
export const GET_LISTAR_TIPOS_MIDIA_FAILURE = 'app/GET_LISTAR_TIPOS_MIDIA_FAILURE';
